version: "3.5"


services:
  db:
    container_name: postgres
    restart: always
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - botnet

  redis:
    container_name: redis_db
    restart: always
    image: redis:5
    volumes:
      - redis_data:/data
    networks:
      - botnet
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes

  callback_listener:
    container_name: fondy_listener
    build:
      context: ./callback_listener/
    depends_on:
      - db
    restart: always
    networks:
      - botnet
    ports:
      - 1001:1001
    command: python fondy_callback_listener.py

  adminer:
    container_name: pg_adminer
    image: adminer
    restart: always
    ports:
      - 8000:8000
    networks:
      - botnet


volumes:
  pg_data:
    name: pg_volume
    driver: local
  redis_data:
    name: redis_volume
    driver: local


networks:
  botnet:
    driver: bridge